### ISSUE TITLE
Dalmatians Flair not supported?

### ISSUE THREAD

**Issue by banzaiTP** [BobSmithIV/TagProRandomFlairs#1]
Not sure if you wanted comments here. So not complaining or anything. Just letting you know when I installed the script it said dalmatians was not supported and to come here or message you. Figured I'd post here.

If I'm doing something wrong, uhh, whoops. I love the script, so thanks.

**Comment by BobSmithIV** [comment]
Thanks for the heads up, I confess I'd simply misspelt dalmatians!  Serves me right for not having 101 degrees!  That's all fixed now :)
